name: jupyterlab-open-url-parameter
channels:
- conda-forge
dependencies:
- pip
- python=3.10
- pydata-sphinx-theme
- myst-parser
- jupyterlab>=4.0.0,<5
- nodejs=22
- jupyterlite-core>=0.7.0,<0.8
- jupyterlite-sphinx
- pip:
  - ..
