# a mybinder.org-ready environment for demoing jupyterlab_open_url_parameter
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-open-url-parameter-demo
#
name: jupyterlab-open-url-parameter-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.11,<3.12
  - jupyterlab >=4.0.10,<5
  - notebook >=7.0.6,<8
  # labextension build dependencies
  - nodejs >=20,<21
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
